{
  "formatVersion": "1.1",
  "component": {
    "group": "com.faendir.liquibase",
    "module": "script-definition",
    "version": "3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "yllxpd5tevhibd7qghw3dwv3u4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "script-definition-3.0.3.jar",
          "url": "script-definition-3.0.3.jar",
          "size": 6403,
          "sha512": "6f11c17de20e056158ede88f7aad9a187ba60769d41c69f42fb2c43cfb53ab657b32f9687e0a8131844e8c12a93ca0d010732709f10aa3bad5e54251b84f4517",
          "sha256": "b90186089767cb19af32fc4d5740448a03f3837f0739edfe55165de18b26d22a",
          "sha1": "b8257e7d4335ae776bfef5bab50e59e7c0d39a18",
          "md5": "24f359f7ec89d4b3a824c6e653dd5cdf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "script-definition-3.0.3.jar",
          "url": "script-definition-3.0.3.jar",
          "size": 6403,
          "sha512": "6f11c17de20e056158ede88f7aad9a187ba60769d41c69f42fb2c43cfb53ab657b32f9687e0a8131844e8c12a93ca0d010732709f10aa3bad5e54251b84f4517",
          "sha256": "b90186089767cb19af32fc4d5740448a03f3837f0739edfe55165de18b26d22a",
          "sha1": "b8257e7d4335ae776bfef5bab50e59e7c0d39a18",
          "md5": "24f359f7ec89d4b3a824c6e653dd5cdf"
        }
      ]
    }
  ]
}
