{
  "formatVersion": "1.1",
  "component": {
    "group": "com.faendir.liquibase",
    "module": "script-definition",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "4ewl6ci5aja3hd3yiwjpjfqmg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "script-definition-3.0.0.jar",
          "url": "script-definition-3.0.0.jar",
          "size": 6403,
          "sha512": "69cc457a3d2bf1071aa38895f2b5b7b8564bd0361b79a177a91c369d849268d6491e53a94abcbc6c145583754b9b6f5c582eb0fbad4d2a773989b4c0d1201360",
          "sha256": "1e81b98b911f085b5821807b6637a8ed5adc21b9856536daad28acc640b050ee",
          "sha1": "4480650a40cf242e65a6dd58d2293c73191247cb",
          "md5": "20d14cd843fb2c633d8f8a6c82836055"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "script-definition-3.0.0.jar",
          "url": "script-definition-3.0.0.jar",
          "size": 6403,
          "sha512": "69cc457a3d2bf1071aa38895f2b5b7b8564bd0361b79a177a91c369d849268d6491e53a94abcbc6c145583754b9b6f5c582eb0fbad4d2a773989b4c0d1201360",
          "sha256": "1e81b98b911f085b5821807b6637a8ed5adc21b9856536daad28acc640b050ee",
          "sha1": "4480650a40cf242e65a6dd58d2293c73191247cb",
          "md5": "20d14cd843fb2c633d8f8a6c82836055"
        }
      ]
    }
  ]
}
