{
  "formatVersion": "1.1",
  "component": {
    "group": "com.faendir.liquibase",
    "module": "script-definition",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "3i7xtyvfsfac3iyldeuhs4nuhi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "script-definition-3.0.1.jar",
          "url": "script-definition-3.0.1.jar",
          "size": 6403,
          "sha512": "0df0386f1289d46d7db12177bbda33d149233387a99aed62107d1fbabefe91217f7c9b3404a716ba9b8667faef620e10d49ff13739ef65ff2cba4eb0a9fddfd5",
          "sha256": "ef2f7cea2375ae5ded9f49707be7593b890239a013f5d533c16493e102c5f5ac",
          "sha1": "18b390d649588a093fe60339258ace5e31c34c6e",
          "md5": "23ddfef00244d8b077b5db5e237fbaf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "script-definition-3.0.1.jar",
          "url": "script-definition-3.0.1.jar",
          "size": 6403,
          "sha512": "0df0386f1289d46d7db12177bbda33d149233387a99aed62107d1fbabefe91217f7c9b3404a716ba9b8667faef620e10d49ff13739ef65ff2cba4eb0a9fddfd5",
          "sha256": "ef2f7cea2375ae5ded9f49707be7593b890239a013f5d533c16493e102c5f5ac",
          "sha1": "18b390d649588a093fe60339258ace5e31c34c6e",
          "md5": "23ddfef00244d8b077b5db5e237fbaf2"
        }
      ]
    }
  ]
}
